name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          npm install
          npx playwright install-deps
          npx playwright install
      - name: Run tests
        run: npm test
      - name: Post code coverage results to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive coverage folder
        uses: actions/upload-artifact@v3
        with:
          path: coverage/
